# Generated by Django 3.0.2 on 2020-01-24 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sample_database', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='failed_regex_strings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.CharField(max_length=50)),
                ('error', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='acidclean',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField(help_text='Celsius')),
                ('start_time', models.DateTimeField()),
                ('stop_time', models.DateTimeField(blank=True, null=True)),
                ('processed', models.BooleanField(default=False)),
                ('issued_start_user', models.CharField(max_length=50)),
                ('issued_stop_user', models.CharField(blank=True, max_length=50, null=True)),
                ('issued_start_time', models.DateTimeField()),
                ('issued_stop_time', models.DateTimeField(blank=True, null=True)),
                ('diamonds', models.ManyToManyField(blank=True, related_name='_acidclean_diamonds_+', to='sample_database.Sample')),
            ],
        ),
    ]
