# Generated by Django 3.0.2 on 2020-02-01 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_database', '0002_auto_20200129_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='design_object_attachment',
            name='name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
