# Generated by Django 3.0.2 on 2020-02-03 16:44

from django.db import migrations, models
import django.db.models.deletion
import django_enumfield.db.fields
import sample_database.models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_database', '0003_design_object_attachment_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Param',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=5000)),
                ('param_type', django_enumfield.db.fields.EnumField(default=2, enum=sample_database.models.ParamType)),
                ('max_value', models.FloatField()),
                ('min_value', models.FloatField()),
                ('default_value', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='action',
            name='fields',
        ),
        migrations.RemoveField(
            model_name='action_type',
            name='field_names',
        ),
        migrations.RemoveField(
            model_name='data',
            name='fields',
        ),
        migrations.RemoveField(
            model_name='data_type',
            name='field_names',
        ),
        migrations.CreateModel(
            name='ParamValueData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sample_database.Data')),
                ('param', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sample_database.Param')),
            ],
        ),
        migrations.CreateModel(
            name='ParamValueAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sample_database.Action')),
                ('param', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sample_database.Param')),
            ],
        ),
    ]
