# Generated by Django 3.0.2 on 2020-02-03 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sample_database', '0004_auto_20200203_1744'),
    ]

    operations = [
        migrations.CreateModel(
            name='Param_Value_Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sample_database.Action')),
                ('param', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sample_database.Param')),
            ],
        ),
        migrations.CreateModel(
            name='Param_Value_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sample_database.Data')),
                ('param', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sample_database.Param')),
            ],
        ),
        migrations.RemoveField(
            model_name='paramvaluedata',
            name='data',
        ),
        migrations.RemoveField(
            model_name='paramvaluedata',
            name='param',
        ),
        migrations.DeleteModel(
            name='ParamValueAction',
        ),
        migrations.DeleteModel(
            name='ParamValueData',
        ),
    ]
