# Generated by Django 3.0.2 on 2020-02-03 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_database', '0006_auto_20200203_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='param',
            name='default_value',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='param',
            name='description',
            field=models.CharField(blank=True, max_length=5000),
        ),
        migrations.AlterField(
            model_name='param',
            name='max_value',
            field=models.FloatField(default=100),
        ),
        migrations.AlterField(
            model_name='param',
            name='min_value',
            field=models.FloatField(default=0),
        ),
    ]
