# Generated by Django 3.0.2 on 2020-02-03 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_database', '0010_auto_20200203_1814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='params',
        ),
        migrations.RemoveField(
            model_name='data',
            name='params',
        ),
        migrations.AddField(
            model_name='action_type',
            name='params',
            field=models.ManyToManyField(to='sample_database.Param'),
        ),
        migrations.AddField(
            model_name='data_type',
            name='params',
            field=models.ManyToManyField(to='sample_database.Param'),
        ),
    ]
