# Generated by Django 3.0.2 on 2020-02-03 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_database', '0011_auto_20200203_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='action_type',
            name='notes',
            field=models.TextField(blank=True, max_length=5000),
        ),
    ]
