# Generated by Django 3.0.2 on 2020-02-03 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_database', '0012_action_type_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action_type',
            name='params',
            field=models.ManyToManyField(blank=True, to='sample_database.Param'),
        ),
        migrations.AlterField(
            model_name='data_type',
            name='params',
            field=models.ManyToManyField(blank=True, to='sample_database.Param'),
        ),
    ]
