# Generated by Django 3.0.2 on 2020-02-12 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sample_database', '0013_auto_20200203_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='data_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sample_database.Data_Type'),
        ),
    ]
